// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// UserSegmentsColumns holds the columns for the "user_segments" table.
	UserSegmentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user_id", Type: field.TypeString},
		{Name: "segment", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
	}
	// UserSegmentsTable holds the schema information for the "user_segments" table.
	UserSegmentsTable = &schema.Table{
		Name:       "user_segments",
		Columns:    UserSegmentsColumns,
		PrimaryKey: []*schema.Column{UserSegmentsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		UserSegmentsTable,
	}
)

func init() {
}
