// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Rustixir/go-challenge/ent/predicate"
	"github.com/Rustixir/go-challenge/ent/usersegment"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeUserSegment = "UserSegment"
)

// UserSegmentMutation represents an operation that mutates the UserSegment nodes in the graph.
type UserSegmentMutation struct {
	config
	op            Op
	typ           string
	id            *int
	user_id       *string
	segment       *string
	created_at    *time.Time
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*UserSegment, error)
	predicates    []predicate.UserSegment
}

var _ ent.Mutation = (*UserSegmentMutation)(nil)

// usersegmentOption allows management of the mutation configuration using functional options.
type usersegmentOption func(*UserSegmentMutation)

// newUserSegmentMutation creates new mutation for the UserSegment entity.
func newUserSegmentMutation(c config, op Op, opts ...usersegmentOption) *UserSegmentMutation {
	m := &UserSegmentMutation{
		config:        c,
		op:            op,
		typ:           TypeUserSegment,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withUserSegmentID sets the ID field of the mutation.
func withUserSegmentID(id int) usersegmentOption {
	return func(m *UserSegmentMutation) {
		var (
			err   error
			once  sync.Once
			value *UserSegment
		)
		m.oldValue = func(ctx context.Context) (*UserSegment, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().UserSegment.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withUserSegment sets the old UserSegment of the mutation.
func withUserSegment(node *UserSegment) usersegmentOption {
	return func(m *UserSegmentMutation) {
		m.oldValue = func(context.Context) (*UserSegment, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m UserSegmentMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m UserSegmentMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *UserSegmentMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *UserSegmentMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().UserSegment.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetUserID sets the "user_id" field.
func (m *UserSegmentMutation) SetUserID(s string) {
	m.user_id = &s
}

// UserID returns the value of the "user_id" field in the mutation.
func (m *UserSegmentMutation) UserID() (r string, exists bool) {
	v := m.user_id
	if v == nil {
		return
	}
	return *v, true
}

// OldUserID returns the old "user_id" field's value of the UserSegment entity.
// If the UserSegment object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserSegmentMutation) OldUserID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUserID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUserID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUserID: %w", err)
	}
	return oldValue.UserID, nil
}

// ResetUserID resets all changes to the "user_id" field.
func (m *UserSegmentMutation) ResetUserID() {
	m.user_id = nil
}

// SetSegment sets the "segment" field.
func (m *UserSegmentMutation) SetSegment(s string) {
	m.segment = &s
}

// Segment returns the value of the "segment" field in the mutation.
func (m *UserSegmentMutation) Segment() (r string, exists bool) {
	v := m.segment
	if v == nil {
		return
	}
	return *v, true
}

// OldSegment returns the old "segment" field's value of the UserSegment entity.
// If the UserSegment object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserSegmentMutation) OldSegment(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSegment is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSegment requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSegment: %w", err)
	}
	return oldValue.Segment, nil
}

// ResetSegment resets all changes to the "segment" field.
func (m *UserSegmentMutation) ResetSegment() {
	m.segment = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *UserSegmentMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *UserSegmentMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the UserSegment entity.
// If the UserSegment object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserSegmentMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *UserSegmentMutation) ResetCreatedAt() {
	m.created_at = nil
}

// Where appends a list predicates to the UserSegmentMutation builder.
func (m *UserSegmentMutation) Where(ps ...predicate.UserSegment) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the UserSegmentMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *UserSegmentMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.UserSegment, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *UserSegmentMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *UserSegmentMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (UserSegment).
func (m *UserSegmentMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *UserSegmentMutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m.user_id != nil {
		fields = append(fields, usersegment.FieldUserID)
	}
	if m.segment != nil {
		fields = append(fields, usersegment.FieldSegment)
	}
	if m.created_at != nil {
		fields = append(fields, usersegment.FieldCreatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *UserSegmentMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case usersegment.FieldUserID:
		return m.UserID()
	case usersegment.FieldSegment:
		return m.Segment()
	case usersegment.FieldCreatedAt:
		return m.CreatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *UserSegmentMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case usersegment.FieldUserID:
		return m.OldUserID(ctx)
	case usersegment.FieldSegment:
		return m.OldSegment(ctx)
	case usersegment.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown UserSegment field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserSegmentMutation) SetField(name string, value ent.Value) error {
	switch name {
	case usersegment.FieldUserID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUserID(v)
		return nil
	case usersegment.FieldSegment:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSegment(v)
		return nil
	case usersegment.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown UserSegment field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *UserSegmentMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *UserSegmentMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserSegmentMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown UserSegment numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *UserSegmentMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *UserSegmentMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *UserSegmentMutation) ClearField(name string) error {
	return fmt.Errorf("unknown UserSegment nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *UserSegmentMutation) ResetField(name string) error {
	switch name {
	case usersegment.FieldUserID:
		m.ResetUserID()
		return nil
	case usersegment.FieldSegment:
		m.ResetSegment()
		return nil
	case usersegment.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	}
	return fmt.Errorf("unknown UserSegment field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *UserSegmentMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *UserSegmentMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *UserSegmentMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *UserSegmentMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *UserSegmentMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *UserSegmentMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *UserSegmentMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown UserSegment unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *UserSegmentMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown UserSegment edge %s", name)
}
