// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Rustixir/go-challenge/ent/usersegment"
)

// UserSegment is the model entity for the UserSegment schema.
type UserSegment struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID string `json:"user_id,omitempty"`
	// Segment holds the value of the "segment" field.
	Segment string `json:"segment,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserSegment) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usersegment.FieldID:
			values[i] = new(sql.NullInt64)
		case usersegment.FieldUserID, usersegment.FieldSegment:
			values[i] = new(sql.NullString)
		case usersegment.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserSegment fields.
func (us *UserSegment) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usersegment.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			us.ID = int(value.Int64)
		case usersegment.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				us.UserID = value.String
			}
		case usersegment.FieldSegment:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field segment", values[i])
			} else if value.Valid {
				us.Segment = value.String
			}
		case usersegment.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				us.CreatedAt = value.Time
			}
		default:
			us.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserSegment.
// This includes values selected through modifiers, order, etc.
func (us *UserSegment) Value(name string) (ent.Value, error) {
	return us.selectValues.Get(name)
}

// Update returns a builder for updating this UserSegment.
// Note that you need to call UserSegment.Unwrap() before calling this method if this UserSegment
// was returned from a transaction, and the transaction was committed or rolled back.
func (us *UserSegment) Update() *UserSegmentUpdateOne {
	return NewUserSegmentClient(us.config).UpdateOne(us)
}

// Unwrap unwraps the UserSegment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (us *UserSegment) Unwrap() *UserSegment {
	_tx, ok := us.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserSegment is not a transactional entity")
	}
	us.config.driver = _tx.drv
	return us
}

// String implements the fmt.Stringer.
func (us *UserSegment) String() string {
	var builder strings.Builder
	builder.WriteString("UserSegment(")
	builder.WriteString(fmt.Sprintf("id=%v, ", us.ID))
	builder.WriteString("user_id=")
	builder.WriteString(us.UserID)
	builder.WriteString(", ")
	builder.WriteString("segment=")
	builder.WriteString(us.Segment)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(us.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UserSegments is a parsable slice of UserSegment.
type UserSegments []*UserSegment
