// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// UserSegment is the predicate function for usersegment builders.
type UserSegment func(*sql.Selector)
